spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.continue-on-error=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=mysupersecretkeymysupersecretkeymysupersecretkey123

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true